### ISSUE TITLE
Move manual ViewHelper ref for 8.7 into this repo

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper#13]
https://docs.typo3.org/m/typo3/guide-extbasefluid/8.7/en-us/Fluid/ViewHelper/Index.html

to switch versions with version selector.

---

Disclaimer: I don't know if this is easily possible. But it would probably be helpful to have it all in one place.

**Comment by DanielSiepmann** [comment]
Not sure whether that's possible. I would not invest time into that, as the process is completely different and the Reference should be auto generated anyway.

Can we close this issue, or would you like to invest time on your own?

**Comment by sypets** [comment]
I agree, if this is not something that is easily doable, I would not invest time.
