### ISSUE TITLE
Broken Syntax for Switch

### ISSUE THREAD

**Issue by linawolf** [TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper#19]
The syntax of code examples here is broken, But there is no edit me on Github Button yet:

https://docs.typo3.org/other/typo3/view-helper-reference/master/en-us/typo3fluid/fluid/latest/Switch.html

**Comment by DanielSiepmann** [comment]
The startpage explained why it's broken, it's the same for all ViewHelper below `typo3fluid`:

> Right now this might look ugly in some places, e.g. = EXAMPLE = and rendered HTML markup like <code>. This will be polished in the future. The current state still is much better then nothing.

And there is no Edit me on GitHub for a reason, see startpage:

> This is a complete reference of all available Fluid ViewHelper within TYPO3 CMS. This documentation is generated from PHP Source code of TYPO3 CMS.

How can we communicate this in a better way?

**Comment by sypets** [comment]
@DanielSiepmann Once broken formatting is fixed, I think it will be less of a problem. Can anyone help with this?

Also, you already suggested adding a note to every page automatically, I think. Not everyone looks at the start page, if people google they will directly load a subpage. So information on the start page will not get read by everyone.

**Comment by DanielSiepmann** [comment]
So this is the "ok" for adding the hint to all pages? Not everyone liked the idea. But Fix for rendering is coming already.

Still we would miss the contribution info.

**Comment by sypets** [comment]
I don't remember or missed the discussion so I don't know what the objections were against the hint on all pages. Anyway, might be better to create a dedicated issue or decision for that. Closing this now.
