### ISSUE TITLE
Currently rendered ViewHelper reference start page does not use Documentation/Index.rst

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper#23]
* people keep asking why is Fluid ViewHelper rendering broken
*  and keep pushing PR

The information on the start page currently does not reflect this.There is more information in README.rst and CONTRIBUTING.rst but that is not even linked to from the start page.

[Documentation/Index.rst](https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper/blob/master/Documentation/Index.rst) has already been updated but does not appear to get used. 

Updating the start page would not solve the problem because people keep landing on subpages and asking about the rendering. But it is at least a start.

------------

> The current state still is much better then nothing.

I would remove this

>  Also notice that package names are not 1:1 Composer packages. cms- is striped.

striped?

**Comment by sypets** [comment]
Closing, older than 2 years. No high priority.

**Comment by alexander-nitsche** [comment]
The ViewHelper rendering has been fixed for TYPO3 v10 and v11 lately and the Documentation/Index.rst is now kept and not overwritten anymore by the automatically rendered one. Would you check if the "Fluid ViewHelper rendering broken" is fixed now?

**Comment by sypets** [comment]
Thanks for clearing that up.

Yes, it looks like the rendered page is identical with Documentation/Index.rst.
