### ISSUE TITLE
Switching to 8.7 from 9.5 and master results in 403 forbidden for typo3fluid/fluid

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper#24]
When switching to 8.7 from either https://docs.typo3.org/other/typo3/view-helper-reference/master/en-us/typo3fluid/fluid/latest/Index.html or https://docs.typo3.org/other/typo3/view-helper-reference/9.5/en-us/typo3fluid/fluid/latest/Index.html the user receives a 403 forbidden.

The reason is that there is a different file structure for 8.7, it should be https://docs.typo3.org/other/typo3/view-helper-reference/8.7/en-us/typo3fluid/fluid/ but actually is https://docs.typo3.org/other/typo3/view-helper-reference/8.7/en-us/typo3fluid/fluid/2.5.5/Index.html.

This is due the fact that 8.7 was generated once by hand and deployed by hand.

**Comment by sypets** [comment]
Can we do something about this?

**Comment by linawolf** [comment]
We are not doing changes about eLTS versions anymore
