### ISSUE TITLE
f:debug is missing "title" argument documentation

### ISSUE THREAD

**Issue by remonator** [TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper#25]
The documentation for the `f:debug` ViewHelper ([here](https://docs.typo3.org/other/typo3/view-helper-reference/master/en-us/typo3fluid/fluid/latest/Debug.html)) is missing the argument "title", although it is present in the code example.

Maybe this is the wrong place - it is also not initialized as argument in [DebugViewHelper.php:55](https://github.com/TYPO3/Fluid/blob/7712d383a947333be3291d9e9b1630d44275c563/src/ViewHelpers/DebugViewHelper.php#L55)

**Comment by sypets** [comment]
Please make the change directly in the FLUID source code repo: https://github.com/TYPO3/Fluid

see also Contributing.rst in this repo: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper/blob/master/CONTRIBUTING.rst
