### ISSUE TITLE
Change description of f:uri.image

### ISSUE THREAD

**Issue by Zillion01** [TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper#26]
The documentation states

_Resizes a given image (if required) and returns its relative path._

However it also returns the paths of non images with a filereference when setting treatIdAsReference.

**Comment by sypets** [comment]
I am closing here. This must be handled in the TYPO3 source code. Ideally make the change yourself by either:

1. Editing the file directly on GitHub: https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/fluid/Classes/ViewHelpers/Uri/ImageViewHelper.php

2. or following the contribution workflow (this requires that you work locally with git):  https://docs.typo3.org/m/typo3/guide-contributionworkflow/master/en-us/BugfixingAZ/Index.html


For contributing to the ViewHelper reference, please see: https://github.com/TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper/blob/master/CONTRIBUTING.rst

This reference is automatically generated. The change must be made in the source code (in the comments). 

The source for f:uri.image is in the TYPO3 CMS "fluid" system extension: 

`Classes\ViewHelpers\ ...`

https://github.com/TYPO3/TYPO3.CMS/blob/master/typo3/sysext/fluid/Classes/ViewHelpers/Uri/ImageViewHelper.php
