### ISSUE TITLE
Ordering of subtopics in TOC not right

### ISSUE THREAD

**Issue by beyring** [TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper#29]
https://docs.typo3.org/other/typo3/view-helper-reference/9.5/en-us/typo3fluid/fluid/latest/Index.html

Subtopics cache and format are not ordered correctly as I assume the ordering for the navigation should be alphabetical. Both are on top of the list. 

Btw: The button 'Edit mit on github' was quite ueseful - will it be integrated again?

**Comment by linawolf** [comment]
Chapters that have subchapters come on top, just like is done with operating systems and folder. The new extended doctree should make this more clear as it also shows the subpages.

As this page is auto-generated it is not possible to have a meaningfull "Edit on Github" button. See https://docs.typo3.org/other/typo3/view-helper-reference/main/en-us/Contribution/Index.html
