### ISSUE TITLE
f:render docs display broken

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper#32]
The documentation for `<f:render>` seems to be broken:
![2021-02-15_1](https://user-images.githubusercontent.com/59036/107926724-53f01880-6f76-11eb-8b4c-3a8b31dad4b7.png)

https://docs.typo3.org/other/typo3/view-helper-reference/master/en-us/typo3fluid/fluid/latest/Render.html

**Comment by cweiske** [comment]
The examples are gone now, and the rendering is not broken anymore.
https://docs.typo3.org/other/typo3/view-helper-reference/main/en-us/typo3/fluid/latest/Render.html

Too bad that the examples are gone, though.

**Comment by sypets** [comment]
@cweiske You are referring to 2 different things:

1. render in typo3fluid: (package [typo3fluid/fluid](https://github.com/TYPO3/Fluid))

*  docs: https://docs.typo3.org/other/typo3/view-helper-reference/master/en-us/typo3fluid/fluid/latest/Render.html
* source: https://github.com/TYPO3/Fluid/blob/main/src/ViewHelpers/RenderViewHelper.php

2. render in typo3 EXT:fluid 

* docs: https://docs.typo3.org/other/typo3/view-helper-reference/main/en-us/typo3/fluid/latest/Render.html
* source: https://github.com/TYPO3/typo3/blob/main/typo3/sysext/fluid/Classes/ViewHelpers/RenderViewHelper.php



Originally, you reported a problem in 1. This contains examples. The rendering looks ok.

The TYPO3 EXT:fluid render does not contain examples.

Notice also the 4 different namespaces in the menu:

![image](https://user-images.githubusercontent.com/13206455/182293979-85c10115-b035-4777-bf68-c65b6233e167.png)

Closing
