### ISSUE TITLE
f:switch doc rendering broken

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper#33]
The f:switch documentation does not render as intended:
![2021-02-18](https://user-images.githubusercontent.com/59036/108318387-09fa7300-71c0-11eb-9586-f5435682c0c8.png)

https://docs.typo3.org/other/typo3/view-helper-reference/master/en-us/typo3fluid/fluid/latest/Switch.html

**Comment by linawolf** [comment]
It is resolved on main an 11.5 and will not be changed anymore for 10.4
