### ISSUE TITLE
Feature request: display information that Viewhelper is deprecated (if @dreprecated annotation exists for class)

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper#38]
be.container ViewHelper was deprecated, see https://github.com/TYPO3/typo3/blob/master/typo3/sysext/fluid/Classes/ViewHelpers/Be/ContainerViewHelper.php

> * :file:`EXT:your_extension/Resources/Public/JavaScript/Library2.js`
> * will be loaded, plus some inline labels for usage in JS code.
>  *
> * @deprecated since v11, will be removed in v12.

But this is not reflected on the rendered page: https://docs.typo3.org/other/typo3/view-helper-reference/master/en-us/typo3/fluid/latest/Be/Container.html

Perhaps there is a way to interpret the `@deprecated` and add a visible note about the deprecation to the generated .rst.

**Comment by linawolf** [comment]
I talked with @lolli42  about this. The deprecation information is currently not contained in the xsd generated by https://github.com/TYPO3/Fluid.SchemaGenerator. And that is the information we are rendering. Lolli plans to work on the xsd generation later this year

**Comment by linawolf** [comment]
@lolli42 How is the Status of the Fluid Scheme Generator? When can we expect to display information on deprecation?

**Comment by linawolf** [comment]
So we fixed it manually for v11.5, will be displayed automatically in future versions. Thanks for reporting!
