### ISSUE TITLE
Define general guidelines for formatting in ViewHelper comments

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper#5]
**Goal: Make it as easy as possible for contributors.**

This should probably be defined separately for

* the TYPO3 core
* for [Fluid](https://github.com/TYPO3/Fluid)

And I guess it would be best to put it in the Contribution Guide for the core and CONTRIBUTING guidelines in fluid (for standalone version).

Before people use various kinds of markup or despair at the difficulties of which markup to use, it might be a good idea to give general guidelines for markup.

Additionally, it might be helpful to use only a small subset of markup, maybe even one that is very similar for reStructuredText and Markdown. 

See ["Common markup for Markdown and reStructuredText"](https://gist.github.com/dupuy/1855764)

Related: PR #2

**Comment by sypets** [comment]
Formatting should be defined in TYPO3 core.

**Comment by linawolf** [comment]
This is a topic for the Core or the Fluid standalone package, not something we can solve here.
