### ISSUE TITLE
Link to php manual, for str_pad is broken 

### ISSUE THREAD

**Issue by h2000x** [TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper#50]
On the page for format.padding (https://docs.typo3.org/other/typo3/view-helper-reference/main/en-us/typo3/fluid/latest/Format/Padding.html) the link to php manual is broken. 

The correct link is:
https://www.php.net/manual/en/function.str-pad

**Comment by linawolf** [comment]
Is addressed here: https://review.typo3.org/c/Packages/TYPO3.CMS/+/76566
