### ISSUE TITLE
Info for feature <f:else if="{other-var} ... is missing

### ISSUE THREAD

**Issue by neonaut** [TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper#69]
**Example for if - then - elseif - else**

```
<f:if condition="{var} == 'something'">
    <f:then>do something</f:then>
    <f:else if="{other-var} == 'something else'">do something else</f:else>
    <f:else>do the other thing</f:else>
</f:if>
```

https://stackoverflow.com/questions/29461381/fluid-if-then-elseif-else

**Comment by linawolf** [comment]
Changes would have to be made in the Fluid project: https://github.com/TYPO3/Fluid/blob/main/src/ViewHelpers/IfViewHelper.php
