### ISSUE TITLE
Use extra .rst files instead of comments for documentation of ViewHelpers?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper#7]
If I am not mistaken, it is currently not possible to prerender changes in the ViewHelper documentation (because they are documented in comments).

Suggestions:

* think about using additional .rst files to manage the documentation and not document in comments

**Comment by sypets** [comment]
This is a major change and probably should be discussed with maintainers first.

**Comment by alexander-nitsche** [comment]
Locally rendering the ViewHelpers documentation can be done for example by 

(1) generating the reST documentation files with the script of https://github.com/TYPO3-Documentation/t3docs-ci-deploy/blob/main/.github/workflows/fluid-viewhelper.yml, and 
(2) compiling the extract with the usual t3docs rendering toolchain.

**Comment by linawolf** [comment]
This is not desired by @lolli42 , the main maintainer of Fluid
