### ISSUE TITLE
ReST Files are not rendered anymore

### ISSUE THREAD

**Issue by FlorianT03** [TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper#75]
There have been some new changes, but it does not get rendered, so the new Information is missing. 

For Example how it should be: https://docs.typo3.org/other/typo3/view-helper-reference/main/en-us/typo3/fluid/latest/Link/Typolink.html#addquerystring

Outdated Information: https://docs.typo3.org/other/typo3/view-helper-reference/main/en-us/typo3/fluid/latest/Link/Page.html#addquerystring

I have looked into the Core Files, but it's correct there, so it must be a rendering problem.

**Comment by linawolf** [comment]
I fixed the generation of the rst files
