### ISSUE TITLE
Link f:image.width to typoscript reference

### ISSUE THREAD

**Issue by cweiske** [TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper#83]
f:image.height should link to the typoscript reference.

The rST patch would be 
```
- See imgResource.width for possible options.
+ See :ref:`imgResource.width <t3tsref:imgresource-width>` for possible options.
```

.. but I do not know if that works when added to the typo3 source code.

- https://docs.typo3.org/other/typo3/view-helper-reference/12.4/en-us/typo3/fluid/latest/Image.html#image_height
- https://docs.typo3.org/m/typo3/reference-typoscript/12.4/en-us/Functions/Imgresource.html#width

**Comment by linawolf** [comment]
Such changes would have to be made in https://github.com/TYPO3/typo3/blob/main/typo3/sysext/fluid/Classes/ViewHelpers/ImageViewHelper.php
