### ISSUE TITLE
"Edit n GitHub" button for automatically generated ViewHelper reference should link to source code?

### ISSUE THREAD

**Issue by sypets** [TYPO3-Documentation/TYPO3CMS-Reference-ViewHelper#9]
I realize this might be a little difficult because we have generated docs from 2 source repos (core and fluid) and the paths of the files would need to be determined as well, but it would be quite helpful because:

* Make it easier to contribute (esp. for current non-core / Fluid contributors)

Example page: https://docs.typo3.org/other/typo3/view-helper-reference/main/en-us/typo3/core/latest/Form/TypoScriptConstants.html

Alternatives:

* show a banner on the top of the page with information about how to contribute and where the source code is

**Comment by alexander-nitsche** [comment]
Related: #63

**Comment by linawolf** [comment]
It is unfortunarily now possible for now. We therefore had to remove the "Edit on Github" Button and add a contribution page instead
